import React from "react"
import CodeBlock from "@theme/CodeBlock"
import { Link } from "react-router-dom"
import { Tooltip } from "react-tooltip"
export default function PreviewrTqya3vrZoXSWo3Na(){
  return (<Tooltip
  id="preview__rTqya3vrZoXSWo3Na"
  place="top"
  clickable
>
  <small>
    <dfn>
      <dt><code className="react-tooltip__dt"><span>SPA</span></code><em>&#x20;aka&#x20;</em><code className="italic font-bold"><span>SPA</span></code></dt>
      <dd>
        <blockquote className="react-tooltip__dd"><span><Link to="/wiki/Computer-Science/Computer-Language/Computer/Software/Domain/Web-Dev/Web-App"><span>Web&#x20;App</span></Link><span>&#x20;run&#x20;on&#x20;single&#x20;</span><Link to="/wiki/Computer-Science/Computer-Network/Network-Scope/Internet/WWW/Web-Site/Web-Page"><span>Web&#x20;Page</span></Link><span>&#x20;by&#x20;</span><Link to="/wiki/Computer-Science/Computer-Language/Computer/Software/Domain/Web-Dev/Web-App/SPA/Thick-Client"><span>Thick&#x20;Client</span></Link><span>&#x20;with&#x20;seamless&#x20;functionality&#x20;ie&#x20;</span><Link to="/wiki/Computer-Science/Computer-Language/Computer/Software/Domain/Web-Dev/Web-App/Client-Routing"><code>CSR</code></Link><span>&#x20;</span></span></blockquote>
      </dd>
    </dfn>
    <cite className="react-tooltip__ref-header">Cited 4 times</cite>
    <ol className="font-semibold"><li><cite className="react-tooltip__ref-list"><span>to&#x20;make&#x20;</span><Link to="/wiki/Computer-Science/Computer-Language/Computer/Software/Domain/Web-Dev/Web-App/SPA"><span>SPA</span></Link><span>&nbsp;↔&nbsp;</span><span>to&#x20;use&#x20;state&#x20;&#x26;&#x20;lifecycle&#x20;methods</span></cite></li><li><cite className="react-tooltip__ref-list"><Link to="/wiki/Computer-Science/Computer-Network/Network-Scope/Internet/WWW/Search-Engine/Web-Crawler"><span>Web&#x20;Crawler</span></Link><span>&#x20;bad&#x20;compat&#x20;with&#x20;</span><Link to="/wiki/Computer-Science/Computer-Language/Computer/Software/Domain/Web-Dev/Web-App/SPA"><span>SPA</span></Link><span>&#x20;</span><Link to="/wiki/Computer-Science/Computer-Language/Computer/Software/Domain/Web-Dev/Web-App/Client-Side-Rendering"><span>Client&#x20;Side&#x20;Rendering</span></Link><span>&#x20;</span><Link to="/wiki/Computer-Science/Computer-Network/Network-Scope/Internet/WWW/Web-Site/Web-Page"><span>Web&#x20;Page</span></Link><span>,&#x20;worsens&#x20;</span><Link to="/wiki/Computer-Science/Computer-Network/Network-Scope/Internet/WWW/Search-Engine/SEO"><span>SEO</span></Link><span>&#x20;</span></cite></li><li><cite className="react-tooltip__ref-list"><code>docusaurus</code><span>&nbsp;↔&nbsp;</span><Link to="/wiki/React/React-Stack"><code>React Framework</code></Link><span>&#x20;</span><Link to="/wiki/Computer-Science/Computer-Network/Network-Scope/Internet/WWW/Web-Site/SSG"><span>SSG</span></Link><span>&#x20;for&#x20;</span><Link to="/wiki/Dev-tool/API"><span>API</span></Link><span>&#x20;docs&#x20;as&#x20;</span><Link to="/wiki/Computer-Science/Computer-Language/Computer/Software/Domain/Web-Dev/Web-App/SPA"><span>SPA</span></Link><span>&#x20;with&#x20;built-in&#x20;</span><Link to="/wiki/Computer-Science/Computer-Language/Computer/Software/Domain/Web-Dev/Web-App/Client-Routing/Routing"><span>Routing</span></Link><span>&#x20;+&#x20;</span><Link to="/wiki/Computer-Science/Computer-Language/Markup-Language/Markdown/MDX"><span>MDX</span></Link><span>&#x20;support&#x20;</span></cite></li><li><cite className="react-tooltip__ref-list"><span>Client&#x20;Routing</span><span>&nbsp;↔&nbsp;</span><Link to="/wiki/Computer-Science/Computer-Language/Computer/Software/Domain/Web-Dev/Web-App/SPA"><span>SPA</span></Link><span>&#x20;</span><Link to="/wiki/Computer-Science/Computer-Language/Computer/Software/Domain/Web-Dev/Web-App/Client-Routing/Routing"><span>Routing</span></Link><span>&#x20;to&#x20;nav&#x20;within&#x20;</span><Link to="/wiki/Computer-Science/Computer-Language/Computer/Software/Domain/Web-Dev/Web-App"><span>Web&#x20;App</span></Link><span>&#x20;w/o&#x20;page&#x20;refresh,&#x20;via&#x20;</span><Link to="/wiki/Computer-Science/Computer-Language/Computer/Software/Domain/Web-Dev/Web-App/SPA/Thick-Client"><span>Thick&#x20;Client</span></Link><span>&#x20;</span><Link to="/wiki/JS"><span>JS</span></Link><span>&#x20;</span></cite></li></ol>
    
    </small></Tooltip>)
}