import React from "react"
import CodeBlock from "@theme/CodeBlock"
import { Link } from "react-router-dom"
import { Tooltip } from "react-tooltip"
export default function Previewg83rHB5nufN3cDM5N(){
  return (<Tooltip
  id="preview__g83rHB5nufN3cDM5N"
  place="top"
  clickable
>
  <small>
    <dfn>
      <dt><code className="react-tooltip__dt"><span>SSG</span></code><em>&#x20;aka&#x20;</em><code className="italic font-bold"><span>SSG</span></code><span>&#x2C;&#x20;</span><code className="italic font-bold"><span>Static&#x20;Site&#x20;Generation</span></code><span>&#x2C;&#x20;</span><code className="italic font-bold"><span>Static&#x20;Site&#x20;Generator</span></code><span>&#x2C;&#x20;</span><code className="italic font-bold"><span>Static&#x20;Generation</span></code></dt>
      <dd>
        <blockquote className="react-tooltip__dd"><span><span>(</span><em>process</em><span>)&#x20;to&#x20;</span><Link to="/wiki/React/React-Stack/Nextjs/Next-Concepts/Pre-render"><span>Pre-render</span></Link><span>&#x20;</span><Link to="/wiki/HTML"><span>HTML</span></Link><span>&#x20;</span><Link to="/wiki/Computer-Science/Computer-Network/Network-Node/Server/Static-Web-Server/Static-Content"><span>Static&#x20;Content</span></Link><span>&#x20;at&#x20;</span><b>build&#x20;time</b><span>&#x20;for&#x20;</span><Link to="/wiki/Computer-Science/Computer-Language/Computer/Software/Domain/Web-Dev/Web-App/SPA/Thin-Client"><span>Thin&#x20;Client</span></Link><span>&#x20;</span></span></blockquote>
      </dd>
    </dfn>
    <cite className="react-tooltip__ref-header">Cited 7 times</cite>
    <ol className="font-semibold"><li><cite className="react-tooltip__ref-list"><span>Next.js</span><span>&nbsp;↔&nbsp;</span><span>fullstack&#x20;</span><Link to="/wiki/React/React-Stack"><code>React Framework</code></Link><span>&#x20;for&#x20;</span><Link to="/wiki/Computer-Science/Computer-Network/Network-Scope/Internet/WWW/Web-Site/SSG"><span>SSG</span></Link><span>&#x20;&#x26;&#x20;now&#x20;official&#x20;react&#x20;team&#x20;approval?!&#x20;headless&#x20;CMS</span></cite></li><li><cite className="react-tooltip__ref-list"><code>renderToStaticMarkup()</code><span>&nbsp;↔&nbsp;</span><Link to="/wiki/React/React-API/ReactDOM-API/react-dom-server/ReactDOMServer"><code>ReactDOMServer</code></Link><span>&#x20;</span><Link to="/wiki/JS/JS-Language/Object/Function/function"><span>function</span></Link><span>&#x20;to&#x20;</span><Link to="/wiki/Computer-Science/Computer-Network/Network-Scope/Internet/WWW/Web-Site/SSG"><span>SSG</span></Link><span>&#x20;as&#x20;raw&#x20;HTML</span></cite></li><li><cite className="react-tooltip__ref-list"><span>Gatsby</span><span>&nbsp;↔&nbsp;</span><Link to="/wiki/Computer-Science/Computer-Network/Network-Scope/Internet/WWW/Web-Site/SSG"><span>SSG</span></Link><span>&#x20;for&#x20;pure&#x20;blogs.&#x20;</span><Link to="/wiki/React/React-Stack/Nextjs"><span>Next.js</span></Link><span>&#x20;alt&#x20;for&#x20;pure&#x20;static&#x20;sites.&#x20;412K&#x20;vs&#x20;next&#x20;3.5M&#x20;WDL.&#x20;</span><Link to="/wiki/Computer-Science/Computer-Language/Programming-Language/DSL/Query-Language/GraphQL"><span>GraphQL</span></Link></cite></li><li><cite className="react-tooltip__ref-list"><span>Nextra</span><span>&nbsp;↔&nbsp;</span><span>opinionated&#x20;</span><Link to="/wiki/Computer-Science/Computer-Network/Network-Scope/Internet/WWW/Web-Site/SSG"><span>SSG</span></Link><span>&#x20;solution&#x20;for&#x20;</span><Link to="/wiki/React/React-Stack/Nextjs"><code>nextjs</code></Link><span>&#x20;</span></cite></li><li><cite className="react-tooltip__ref-list"><code>docusaurus</code><span>&nbsp;↔&nbsp;</span><Link to="/wiki/React/React-Stack"><code>React Framework</code></Link><span>&#x20;</span><Link to="/wiki/Computer-Science/Computer-Network/Network-Scope/Internet/WWW/Web-Site/SSG"><span>SSG</span></Link><span>&#x20;for&#x20;</span><Link to="/wiki/Dev-tool/API"><span>API</span></Link><span>&#x20;docs&#x20;as&#x20;</span><Link to="/wiki/Computer-Science/Computer-Language/Computer/Software/Domain/Web-Dev/Web-App/SPA"><span>SPA</span></Link><span>&#x20;with&#x20;built-in&#x20;</span><Link to="/wiki/Computer-Science/Computer-Language/Computer/Software/Domain/Web-Dev/Web-App/Client-Routing/Routing"><span>Routing</span></Link><span>&#x20;+&#x20;</span><Link to="/wiki/Computer-Science/Computer-Language/Markup-Language/Markdown/MDX"><span>MDX</span></Link><span>&#x20;support&#x20;</span></cite></li></ol>
    <Link to="/wiki/Computer-Science/Computer-Network/Network-Scope/Internet/WWW/Web-Site/SSG#references"><button className="react-tooltip__ref-link">
          View 2 more
        </button></Link>
    </small></Tooltip>)
}