/**
 * Copyright(c) Roger Jiang
 */

import React, { Suspense, lazy } from "react"
import { useColorMode } from "@docusaurus/theme-common"

const FeatureList = lazy(() => import("./FeatureList"))

const PreviewHWLTjZrhernsLocy7 = lazy(
  () => import("../../../static/preview/PreviewHWLTjZrhernsLocy7")
)

export default function HomepageFeatures(): JSX.Element {
  const { isDarkTheme } = useColorMode()

  return (
    <main
      id="features"
      className="flex w-full items-center p-1 sm:p-2 md:p-4 lg:p-6 xl:p-8"
      style={{
        backgroundImage: `url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciPjxwYXRoIGZpbGw9IiMxYTg4NzAiIGQ9Ik0wIDBoNTQwdjQ1MEgweiIvPjxkZWZzPjxsaW5lYXJHcmFkaWVudCBpZD0iYSIgeDE9IjAiIHgyPSIwIiB5MT0iMCIgeTI9IjEwMCUiIGdyYWRpZW50VHJhbnNmb3JtPSJyb3RhdGUoMjYwIDc2OCAzNjkpIiBncmFkaWVudFVuaXRzPSJ1c2VyU3BhY2VPblVzZSI+PHN0b3Agb2Zmc2V0PSIwIiBzdG9wLWNvbG9yPSIjM${
          isDarkTheme ? "DcyODIx" : "0NBRDZF"
        }Ii8+PHN0b3Agb2Zmc2V0PSIxIiBzdG9wLWNvbG9yPSIjMjFhZjkwIi8+PC9saW5lYXJHcmFkaWVudD48cGF0dGVybiBpZD0iYiIgd2lkdGg9IjU1MCIgaGVpZ2h0PSI0NTguMyIgeD0iMCIgeT0iMCIgcGF0dGVyblVuaXRzPSJ1c2VyU3BhY2VPblVzZSIgdmlld0JveD0iMCAwIDEwODAgOTAwIj48ZyBmaWxsLW9wYWNpdHk9Ii4xIj48cGF0aCBmaWxsPSIjNDQ0IiBkPSJNOTAgMTUwIDAgMzAwaDE4MHoiLz48cGF0aCBkPSJNOTAgMTUwIDE4MCAwSDB6Ii8+PHBhdGggZmlsbD0iI0FBQSIgZD0iTTI3MCAxNTAgMzYwIDBIMTgweiIvPjxwYXRoIGZpbGw9IiNEREQiIGQ9Im00NTAgMTUwLTkwIDE1MGgxODB6Ii8+PHBhdGggZmlsbD0iIzk5OSIgZD0iTTQ1MCAxNTAgNTQwIDBIMzYweiIvPjxwYXRoIGQ9Im02MzAgMTUwLTkwIDE1MGgxODB6Ii8+PHBhdGggZmlsbD0iI0RERCIgZD0iTTYzMCAxNTAgNzIwIDBINTQweiIvPjxwYXRoIGZpbGw9IiM0NDQiIGQ9Im04MTAgMTUwLTkwIDE1MGgxODB6Ii8+PHBhdGggZmlsbD0iI0ZGRiIgZD0iTTgxMCAxNTAgOTAwIDBINzIweiIvPjxwYXRoIGZpbGw9IiNEREQiIGQ9Im05OTAgMTUwLTkwIDE1MGgxODB6Ii8+PHBhdGggZmlsbD0iIzQ0NCIgZD0ibTk5MCAxNTAgOTAtMTUwSDkwMHoiLz48cGF0aCBmaWxsPSIjREREIiBkPSJNOTAgNDUwIDAgNjAwaDE4MHoiLz48cGF0aCBkPSJtOTAgNDUwIDkwLTE1MEgweiIvPjxwYXRoIGZpbGw9IiM2NjYiIGQ9Im0yNzAgNDUwLTkwIDE1MGgxODB6Ii8+PHBhdGggZmlsbD0iI0FBQSIgZD0ibTI3MCA0NTAgOTAtMTUwSDE4MHoiLz48cGF0aCBmaWxsPSIjREREIiBkPSJtNDUwIDQ1MC05MCAxNTBoMTgweiIvPjxwYXRoIGZpbGw9IiM5OTkiIGQ9Im00NTAgNDUwIDkwLTE1MEgzNjB6bTE4MCAwLTkwIDE1MGgxODB6Ii8+PHBhdGggZmlsbD0iI0ZGRiIgZD0ibTYzMCA0NTAgOTAtMTUwSDU0MHoiLz48cGF0aCBkPSJtODEwIDQ1MC05MCAxNTBoMTgweiIvPjxwYXRoIGZpbGw9IiNEREQiIGQ9Im04MTAgNDUwIDkwLTE1MEg3MjB6Ii8+PHBhdGggZmlsbD0iI0FBQSIgZD0ibTk5MCA0NTAtOTAgMTUwaDE4MHoiLz48cGF0aCBmaWxsPSIjNDQ0IiBkPSJtOTkwIDQ1MCA5MC0xNTBIOTAweiIvPjxwYXRoIGZpbGw9IiMyMjIiIGQ9Ik05MCA3NTAgMCA5MDBoMTgweiIvPjxwYXRoIGQ9Im0yNzAgNzUwLTkwIDE1MGgxODB6Ii8+PHBhdGggZmlsbD0iI0RERCIgZD0ibTI3MCA3NTAgOTAtMTUwSDE4MHoiLz48cGF0aCBkPSJtNDUwIDc1MCA5MC0xNTBIMzYwem0xODAgMC05MCAxNTBoMTgweiIvPjxwYXRoIGZpbGw9IiM0NDQiIGQ9Im02MzAgNzUwIDkwLTE1MEg1NDB6Ii8+PHBhdGggZmlsbD0iI0FBQSIgZD0ibTgxMCA3NTAtOTAgMTUwaDE4MHoiLz48cGF0aCBmaWxsPSIjNjY2IiBkPSJtODEwIDc1MCA5MC0xNTBINzIweiIvPjxwYXRoIGZpbGw9IiM5OTkiIGQ9Im05OTAgNzUwLTkwIDE1MGgxODB6TTE4MCAwIDkwIDE1MGgxODB6Ii8+PHBhdGggZmlsbD0iIzQ0NCIgZD0ibTM2MCAwLTkwIDE1MGgxODB6Ii8+PHBhdGggZmlsbD0iI0ZGRiIgZD0ibTU0MCAwLTkwIDE1MGgxODB6Ii8+PHBhdGggZD0ibTkwMCAwLTkwIDE1MGgxODB6Ii8+PHBhdGggZmlsbD0iIzIyMiIgZD0ibTAgMzAwLTkwIDE1MEg5MHoiLz48cGF0aCBmaWxsPSIjRkZGIiBkPSJtMCAzMDAgOTAtMTUwSC05MHptMTgwIDBMOTAgNDUwaDE4MHoiLz48cGF0aCBmaWxsPSIjNjY2IiBkPSJtMTgwIDMwMCA5MC0xNTBIOTB6Ii8+PHBhdGggZmlsbD0iIzIyMiIgZD0ibTM2MCAzMDAtOTAgMTUwaDE4MHoiLz48cGF0aCBmaWxsPSIjRkZGIiBkPSJtMzYwIDMwMCA5MC0xNTBIMjcweiIvPjxwYXRoIGZpbGw9IiM0NDQiIGQ9Im01NDAgMzAwLTkwIDE1MGgxODB6Ii8+PHBhdGggZmlsbD0iIzIyMiIgZD0ibTU0MCAzMDAgOTAtMTUwSDQ1MHoiLz48cGF0aCBmaWxsPSIjQUFBIiBkPSJtNzIwIDMwMC05MCAxNTBoMTgweiIvPjxwYXRoIGZpbGw9IiM2NjYiIGQ9Im03MjAgMzAwIDkwLTE1MEg2MzB6Ii8+PHBhdGggZmlsbD0iI0ZGRiIgZD0ibTkwMCAzMDAtOTAgMTUwaDE4MHoiLz48cGF0aCBmaWxsPSIjOTk5IiBkPSJtOTAwIDMwMCA5MC0xNTBIODEweiIvPjxwYXRoIGQ9Im0wIDYwMC05MCAxNTBIOTB6Ii8+PHBhdGggZmlsbD0iIzY2NiIgZD0ibTAgNjAwIDkwLTE1MEgtOTB6Ii8+PHBhdGggZmlsbD0iI0FBQSIgZD0iTTE4MCA2MDAgOTAgNzUwaDE4MHoiLz48cGF0aCBmaWxsPSIjNDQ0IiBkPSJtMTgwIDYwMCA5MC0xNTBIOTB6bTE4MCAwLTkwIDE1MGgxODB6Ii8+PHBhdGggZmlsbD0iIzk5OSIgZD0ibTM2MCA2MDAgOTAtMTUwSDI3MHoiLz48cGF0aCBmaWxsPSIjNjY2IiBkPSJtNTQwIDYwMCA5MC0xNTBINDUweiIvPjxwYXRoIGZpbGw9IiMyMjIiIGQ9Im03MjAgNjAwLTkwIDE1MGgxODB6Ii8+PHBhdGggZmlsbD0iI0ZGRiIgZD0ibTkwMCA2MDAtOTAgMTUwaDE4MHoiLz48cGF0aCBmaWxsPSIjMjIyIiBkPSJtOTAwIDYwMCA5MC0xNTBIODEweiIvPjxwYXRoIGZpbGw9IiNEREQiIGQ9Im0wIDkwMCA5MC0xNTBILTkweiIvPjxwYXRoIGZpbGw9IiM0NDQiIGQ9Im0xODAgOTAwIDkwLTE1MEg5MHoiLz48cGF0aCBmaWxsPSIjRkZGIiBkPSJtMzYwIDkwMCA5MC0xNTBIMjcweiIvPjxwYXRoIGZpbGw9IiNBQUEiIGQ9Im01NDAgOTAwIDkwLTE1MEg0NTB6Ii8+PHBhdGggZmlsbD0iI0ZGRiIgZD0ibTcyMCA5MDAgOTAtMTUwSDYzMHoiLz48cGF0aCBmaWxsPSIjMjIyIiBkPSJtOTAwIDkwMCA5MC0xNTBIODEwem0xODAtNjAwLTkwIDE1MGgxODB6Ii8+PHBhdGggZmlsbD0iI0ZGRiIgZD0ibTEwODAgMzAwIDkwLTE1MEg5OTB6Ii8+PHBhdGggZD0ibTEwODAgNjAwLTkwIDE1MGgxODB6Ii8+PHBhdGggZmlsbD0iIzY2NiIgZD0ibTEwODAgNjAwIDkwLTE1MEg5OTB6Ii8+PHBhdGggZmlsbD0iI0RERCIgZD0ibTEwODAgOTAwIDkwLTE1MEg5OTB6Ii8+PC9nPjwvcGF0dGVybj48L2RlZnM+PHJlY3Qgd2lkdGg9IjEwMCUiIGhlaWdodD0iMTAwJSIgZmlsbD0idXJsKCNhKSIvPjxyZWN0IHdpZHRoPSIxMDAlIiBoZWlnaHQ9IjEwMCUiIGZpbGw9InVybCgjYikiLz48L3N2Zz4`,
      }}
    >
      <style>{`@keyframes slideup {
    from{bottom:-100px;opacity:0} to{bottom:0;opacity:1};
    .slideup {position:relative;animation:slideup 1s}
}`}</style>
      {/* container */}
      <div className="mx-auto my-0 box-border w-full max-w-screen-xl px-4 py-0 2xl:max-w-screen-2xl">
        {/* row */}
        <div className="my-0 ml-[-1rem] mr-[-1rem] flex flex-wrap">
          <Suspense
            fallback={<div style={{ width: "100%", height: "400px" }}></div>}
          >
            <FeatureList />
          </Suspense>
        </div>
      </div>
      <Suspense fallback={null}>
        <PreviewHWLTjZrhernsLocy7 />
      </Suspense>
    </main>
  )
}
