@REM Copyright(c) Roger Jiang

IF EXIST "C:\Users\Z\react-dev\rjdb-map\build.tar" DEL "C:\Users\Z\react-dev\rjdb-map\build.tar"
IF EXIST "C:\Users\Z\react-dev\rjkb-build-vercel\build.tar" DEL "C:\Users\Z\react-dev\rjkb-build-vercel\build.tar"
"C:\Program Files\7-Zip\7z.exe" a -ttar -mx0 -sccUTF-8 -bb0 -bse0 -bsp2 -sdel "-wC:\Users\Z\react-dev\rjkb-build-vercel\" "C:\Users\Z\react-dev\rjkb-build-vercel\del.tar" "C:\Users\Z\react-dev\rjkb-build-vercel\build"

@REM SAFELY DELETE PREVIEW TSX FOLDER
CD "C:\Users\Z\react-dev\rjdb-map\build\preview" && CD "C:\Users\Z\react-dev\rjdb-map\build" &&  rd /s /q "C:\Users\Z\react-dev\rjdb-map\build\preview"

@REM COMPRESS LEFT OVER FILES IN BROTLI AND GZIP
IF NOT EXIST "sitemap.xml.br" "C:\Program Files\PeaZip\res\bin\brotli\brotli.exe" -9 --large_window=27 "C:\Users\Z\react-dev\rjdb-map\build\sitemap.xml"  -o "C:\Users\Z\react-dev\rjdb-map\build\sitemap.xml.br"
IF NOT EXIST "sitemap.xml.gz" "C:\Program Files\7-Zip\7z.exe" a -tgzip -mx9 -mfb=128 -mpass=10 -sccUTF-8 -bb0 -bse0 -bsp2 "-wC:\Users\Z\react-dev\rjdb-map\build\" "C:\Users\Z\react-dev\rjdb-map\build\sitemap.xml.gz" "C:\Users\Z\react-dev\rjdb-map\build\sitemap.xml" 
IF NOT EXIST "sw.js.br" "C:\Program Files\PeaZip\res\bin\brotli\brotli.exe" -9 --large_window=27 "C:\Users\Z\react-dev\rjdb-map\build\sw.js"  -o "C:\Users\Z\react-dev\rjdb-map\build\sw.js.br"
IF NOT EXIST "sw.js.gz" "C:\Program Files\7-Zip\7z.exe" a -tgzip -mx9 -mfb=128 -mpass=10 -sccUTF-8 -bb0 -bse0 -bsp2 "-wC:\Users\Z\react-dev\rjdb-map\build\" "C:\Users\Z\react-dev\rjdb-map\build\sw.js.gz" "C:\Users\Z\react-dev\rjdb-map\build\sw.js" 
@REM COMPRESS LEFT OVER FEEDS
CD "C:\Users\Z\react-dev\rjdb-map\build\blog"
IF NOT EXIST "atom.xml.br" "C:\Program Files\PeaZip\res\bin\brotli\brotli.exe" -9 --large_window=27 "C:\Users\Z\react-dev\rjdb-map\build\blog\atom.xml"  -o "C:\Users\Z\react-dev\rjdb-map\build\blog\atom.xml.br"
IF NOT EXIST "atom.xml.gz" "C:\Program Files\7-Zip\7z.exe" a -tgzip -mx9 -mfb=128 -mpass=10 -sccUTF-8 -bb0 -bse0 -bsp2 "-wC:\Users\Z\react-dev\rjdb-map\build\blog\" "C:\Users\Z\react-dev\rjdb-map\build\blog\atom.xml.gz" "C:\Users\Z\react-dev\rjdb-map\build\blog\atom.xml" 
IF NOT EXIST "feed.json.br" "C:\Program Files\PeaZip\res\bin\brotli\brotli.exe" -9 --large_window=27 "C:\Users\Z\react-dev\rjdb-map\build\blog\feed.json"  -o "C:\Users\Z\react-dev\rjdb-map\build\blog\feed.json.br"
IF NOT EXIST "feed.json.gz" "C:\Program Files\7-Zip\7z.exe" a -tgzip -mx9 -mfb=128 -mpass=10 -sccUTF-8 -bb0 -bse0 -bsp2 "-wC:\Users\Z\react-dev\rjdb-map\build\blog\" "C:\Users\Z\react-dev\rjdb-map\build\blog\feed.json.gz" "C:\Users\Z\react-dev\rjdb-map\build\blog\feed.json" 
IF NOT EXIST "rss.xml.br" "C:\Program Files\PeaZip\res\bin\brotli\brotli.exe" -9 --large_window=27 "C:\Users\Z\react-dev\rjdb-map\build\blog\rss.xml"  -o "C:\Users\Z\react-dev\rjdb-map\build\blog\rss.xml.br"
IF NOT EXIST "rss.xml.gz" "C:\Program Files\7-Zip\7z.exe" a -tgzip -mx9 -mfb=128 -mpass=10 -sccUTF-8 -bb0 -bse0 -bsp2 "-wC:\Users\Z\react-dev\rjdb-map\build\blog\" "C:\Users\Z\react-dev\rjdb-map\build\blog\rss.xml.gz" "C:\Users\Z\react-dev\rjdb-map\build\blog\rss.xml" 

@REM UID for CSS will not match - defer to secondary bat script generated by node
@REM IF EXIST "C:\Users\Z\react-dev\rjdb-map\build\assets\css\styles.54289fcb.css.br" DEL "C:\Users\Z\react-dev\rjdb-map\build\assets\css\styles.54289fcb.css.br"
@REM IF EXIST "C:\Users\Z\react-dev\rjdb-map\build\assets\css\styles.54289fcb.css.gz" DEL "C:\Users\Z\react-dev\rjdb-map\build\assets\css\styles.54289fcb.css.gz"
@REM IF EXIST "C:\Users\Z\react-dev\rjdb-map\build\assets\css\styles.54289fcb.css" "C:\Program Files\PeaZip\res\bin\brotli\brotli.exe" -9 --large_window=27 "C:\Users\Z\react-dev\rjdb-map\build\assets\css\styles.54289fcb.css"  -o "C:\Users\Z\react-dev\rjdb-map\build\assets\css\styles.54289fcb.css.br"
@REM IF EXIST "C:\Users\Z\react-dev\rjdb-map\build\assets\css\styles.54289fcb.css" "C:\Program Files\PeaZip\res\bin\7z\7z.exe" a -tgzip -mx9 -mfb=128 -mpass=10 -sccUTF-8 -bb0 -bse0 -bsp2 "-wC:\Users\Z\react-dev\rjdb-map\build\assets\css\" "C:\Users\Z\react-dev\rjdb-map\build\assets\css\styles.54289fcb.css.gz" "C:\Users\Z\react-dev\rjdb-map\build\assets\css\styles.54289fcb.css" 


@REM DELETE leftover build
IF EXIST "C:\Users\Z\react-dev\rjkb-build-vercel\del.tar" DEL "C:\Users\Z\react-dev\rjkb-build-vercel\del.tar"

@REM CD "C:\Users\Z\react-dev\rjdb-map"
@REM build tar
@REM "C:\Program Files\7-Zip\7z.exe" a -ttar -mx0 -sccUTF-8 -bb0 -bse0 -bsp2 "-wC:\Users\Z\react-dev\rjdb-map\" "C:\Users\Z\react-dev\rjdb-map\build.tar" "C:\Users\Z\react-dev\rjdb-map\build" 
@REM XCOPY /y "C:\Users\Z\react-dev\rjdb-map\build.tar" "C:\Users\Z\react-dev\rjkb-build-vercel"

@REM @REM del vercel-build
@REM DEL "C:\Users\Z\react-dev\rjkb-build-vercel\del.tar"

@REM @REM @REM move build tar
@REM @REM extraction is BUGGED - incomplete & different size every time!
@REM @REM "C:\Program Files\7-Zip\7z.exe" x -aos "-oC:\Users\Z\react-dev\rjkb-build-vercel\" -bb0 -bse0 -bsp2 -pdefault -sccUTF-8 -snz "C:\Users\Z\react-dev\rjkb-build-vercel\build.tar"
@REM @REM DEL "C:\Users\Z\react-dev\rjkb-build-vercel\build.tar"

cd "C:\Users\Z\react-dev\rjdb-map"
tar -cf build.tar build

XCOPY /y "C:\Users\Z\react-dev\rjdb-map\build.tar" "C:\Users\Z\react-dev\rjkb-build-vercel"

cd "C:\Users\Z\react-dev\rjkb-build-vercel"
del "C:\Users\Z\react-dev\rjdb-map\build.tar"
tar -xf build.tar
del build.tar
git add .